version: '3.3'

services:
  db:
   image: mysql:latest
   volumes:
     - db_data:/var/lib/mysql
   restart: always
   networks:
     - wordpressnet
   environment:
     MYSQL_ROOT_PASSWORD: wordpress_blog
     MYSQL_DATABASE: tp_docker
     MYSQL_USER: user123
     MYSQL_PASSWORD: mdp123

  wordpress:
   image: wordpress:latest
   volumes:
     - wordpress_data:/var/www/html
   ports:
     - "8000:80"
   restart: always
   networks:
     - wordpressnet
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: user123
     WORDPRESS_DB_PASSWORD: mdp123
     WORDPRESS_DB_NAME: tp_docker

  phpmyadmin:
    image: phpmyadmin:latest
    volumes:
      - phpmyadmin_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment: 
      PHPMYADMIN_ROOT_PASSWORD: wordpress_blog
      PHPMYADMIN_USER: user123
      PHPMYADMIN_DATABASE: tp_docker

networks:
  wordpressnet:
    driver: bridge

volumes:
  db_data: {}
  wordpress_data: {}
  phpmyadmin_data: {}  
